(function(){var a="sproutcore/standard_theme";if(!SC.BUNDLE_INFO){throw"SC.BUNDLE_INFO is not defined!"
}if(SC.BUNDLE_INFO[a]){return}SC.BUNDLE_INFO[a]={requires:["sproutcore/empty_theme"],styles:["https://www.turnitincdn.com/800404/static.turnitin.com/cv/20141205.1016/sproutcore/standard_theme/en_us/A/stylesheet-packed.css","https://www.turnitincdn.com/800404/static.turnitin.com/cv/20141205.1016/sproutcore/standard_theme/en_us/A/stylesheet.css"],scripts:["https://www.turnitincdn.com/800404/static.turnitin.com/cv/20141205.1016/sproutcore/standard_theme/en_us/A/javascript-packed.js"]}
})();SC.Benchmark.globalStartTime=window.globalStartTime;SC.Benchmark.start("applicationBootStrap",null,window.globalStartTime);
SC.Benchmark.end("applicationBootStrap");SC.Benchmark.start("applicationStartup");
var use_fixtures=NO;var config;Ip.manageParentSession();Dv=SC.Application.create({NAMESPACE:"Dv",VERSION:"0.1.0",init:function(){arguments.callee.base.apply(this,arguments);
Cv.GA.session_start_ts=new Date().getTime();if(use_fixtures){var b=SC.Record.fixtures;
b.set("simulateRemoteResponse",YES);this.set("store",SC.Store.create().from(b))}else{var a=SC.Store.create({removeDataHash:function(e,c){var d=arguments.callee.base.apply(this,arguments);
if(this.records){delete this.records[e]}return d}}).from("Cv.DataSource");this.set("store",a)
}}});Cv.config.mixin({APP_NAME:"Turnitin",PAPER_BOTTOM_BUFFER:450,ALLOW_OR_OPTIONS_IN_ALL_MODES:YES,HIGH_BIBLIO_QUOTE_WARNING:YES,HIGH_QUOTE_THRESHOLD:30,HIGH_BIBLIO_THRESHOLD:15,HIDE_FIRST_TIME_USER_MESSAGE:YES});
Cv.criterionReadMarkSetsController=RubricManagerCore.CriterionReadMarkSetsController.create({readBinding:"Cv.markSetController.content",rubricBinding:"Cv.rubricController.content"});
Cv.markCriterionSelectionController=Cv.MarkCriterionSelectionController.create();
Cv.readMarkCriteriaController=RubricManagerCore.ReadMarkCriteriaController.create({readBinding:"Cv.gradeMarkController.read",rubricBinding:"Cv.rubricController.content",canUseMarkCriteriaAssociationBinding:"Cv.config.CAN_USE_MARK_CRITERIA_ASSOCIATION"});
RubricManagerCore.criteriaController=RubricManagerCore.CriteriaController.create();
RubricManagerCore.currentRubricController=RubricManagerCore.CurrentRubricController.create();
RubricManagerCore.editingRubricController=RubricManagerCore.EditingRubricController.create();
RubricManagerCore.rubricListController=RubricManagerCore.RubricListController.create();
RubricManagerCore.scalesController=RubricManagerCore.ScalesController.create();RubricManagerCore.importController=RubricManagerCore.ImportController.create();
Cv.rubricScoringFeedbackObjectsController=RubricManagerCore.FeedbackScoringController.create({contentBinding:"Cv.rubricScoringController.scoringFeedbackObjects",rubricScoringBinding:"Cv.rubricScoringController.content",rubricBinding:"Cv.rubricController.content",rubricIsLoadedBinding:"Cv.rubricController.isLoaded",store:Dv.store,assignmentStatusBinding:"Cv.assignmentController.status",rubricScoringObjectDidChange:function(){var a=this.get("rubricScoring"),b=this.get("assignmentStatus");
if(a&&a.get("status")===SC.Record.READY_NEW){if((b&SC.Record.BUSY)===0){a.commitRecord()
}}}.observes("rubricScoring","assignmentStatus")});Dv.ApplicationView=SC.View.extend({classController:null,assignmentsController:null,assignmentStudentsController:null,assignmentController:null,paperController:null,paperTextSelectionController:null,servicesController:null,zoomController:null,createChildViews:function(){var g=[];
var e=this._createNavigationBarViewDesign();var c=this.createChildView(e);g.push(c);
var f=this._createInfoBarViewDesign();var a=this.createChildView(f);g.push(a);var b=this._createSplitViewDesign();
var d=this.createChildView(b);g.push(d);this.navigationBarView=c;this.infoBarView=a;
this.splitView=d;this.paperView=d.topLeftView.paperView;this.set("childViews",g)},_createNavigationBarViewDesign:function(){var a=SC.View.design({childViews:"classTitleView demoAssignmentSelectorView assignmentSelectorView networkMonitor roadmapButtonView customHelpLinkButtonView helpButtonView navigationView".w(),layout:{top:0,height:20,left:0,right:0},classNames:["navbar"],networkMonitor:Cv.NetworkMonitorView,classTitleView:SC.LabelView.design({layout:{top:0,bottom:0,left:10,width:100},classNames:["class-label","ellipsis"],content:this.get("classController"),contentValueKey:"title"}),demoAssignmentSelectorView:SC.ButtonView.design({layout:{top:0,bottom:0,left:110,width:245},classNames:["assignment-selector"],isEnabledBinding:SC.Binding.bool("Cv.inDemoMode"),isVisibleBinding:SC.Binding.bool("Cv.inDemoMode"),titleBinding:SC.Binding.oneWay("Cv.assignmentController.title"),action:function(){SC.PickerPane.create({layout:{width:250,height:30},contentView:SC.LabelView.extend({classNames:"demo-assignment-select-notice",autoResizeLayer:YES,value:"_Assignments will be listed here".loc()})}).popup(this)
}}),assignmentSelectorView:Cv.SelectView.design({layout:{top:0,bottom:0,left:110,width:245},classNames:"assignment-selector",anonymousMarkingIsActiveBinding:"Cv.assignmentController.anonymousMarkingIsActive",itemsBinding:"Cv.assignmentsController.content",valueBinding:"Cv.assignmentsController.selectedAssignment",displayTitleBinding:SC.Binding.oneWay("Cv.assignmentController.title"),selectedStudentBinding:"Cv.classController.selectedStudent",itemTitleKey:"listingDisplay",positionMenuBelow:YES,toolTip:function(){if(this.get("isDisabledByConfig")){return""
}return"_Navigate to other submissions for this student".loc()}.property("isDisabledByConfig").cacheable(),inDemoModeBinding:"Cv.inDemoMode",isOverAssignmentLimitBinding:"Cv.assignmentController.isOverAssignmentLimit",isHiddenByConfigBinding:"Cv.config.HIDE_ASSIGNMENT_NAVIGATION",isDisabledByConfigBinding:"Cv.config.DISABLE_ASSIGNMENT_NAVIGATION",isVisible:function(){if(this.get("isHiddenByConfig")){return NO
}if(Cv.get("inDemoMode")){return NO}else{return !Cv.classController.get("isOverAssignmentLimit")?YES:NO
}}.property("inDemoMode","isOverAssignmentLimit","isHiddenByConfig").cacheable(),displaySelectedItem:function(){if(Cv.demoNotice()){return
}var b=this.get("value");var c={fn:function(d){d.callee.base.apply(this,d);_gaq.push(["_trackEvent",Cv.GA.CATEGORY_ASSIGNMENT_NAV,Cv.GA.ACTION_MENU_SELECTED,Cv.GA.getSessionUUID()])
},target:this,args:arguments};Cv.editingRegistryController.tryToPerform(c);if(this.getPath("value.anonymousMarkingIsActive")){this.set("value",b);
alert("_The assignment you've selected is Anonymous Marking only. Go to this assignment using the assignment inbox.".loc())
}},isEnabled:function(){return !(this.get("isDisabledByConfig")||this.get("anonymousMarkingIsActive")||this.get("selectedStudent.isNonEnrolledStudent"))
}.property("selectedStudent","anonymousMarkingIsActive","isDisabledByConfig").cacheable()}),customHelpLinkButtonView:SC.ButtonView.design({layout:{top:0,left:500,width:93},classNames:["help-button"],title:"_help".loc()=="_help"?"help":"_help".loc(),isVisibleBinding:SC.Binding.bool("Cv.config.SHOW_CUSTOM_HELP_LINK"),action:function(){var c=Ip.getQueryStringParameter("student_user");
var b=c?Cv.config.CUSTOM_HELP_LINK_STUDENT:Cv.config.CUSTOM_HELP_LINK_INSTRUCTOR;
window.open(b)}}),roadmapButtonView:SC.ButtonView.design({layout:{top:0,height:20,right:265,width:113},classNames:["roadmap"],icon:"https://www.turnitincdn.com/800404/static.turnitin.com/cv/20141205.1016/dv/en_us/A/resources/images/roadmap.png",title:"_Roadmap".loc(),action:function(){window.open("/uservoice.asp")
},lang:null,langBinding:"Cv.lang",toolTip:function(){var b=this.get("lang");if(b!=="en_us"){return"_English only".loc()
}}.property("lang").cacheable(),isVisibleBinding:SC.Binding.oneWay("Cv.showRoadmap").bool()}),helpButtonView:SC.ButtonView.design({layout:{top:0,height:20,right:189,width:60},classNames:"help-button".w(),title:"_Help".loc(),isVisible:0,urls:SC.Object.create({0:SC.Object.create({instructor:Cv.get("helpSiteUrl")+"/help/cv/help-instructor.html",student:Cv.get("helpSiteUrl")+"/help/cv/help-student.html"}),1:SC.Object.create({instructor:Cv.get("helpSiteUrl")+"/help/cv/or-help-instructor.html",student:Cv.get("helpSiteUrl")+"/help/cv/or-help-student.html"}),2:SC.Object.create({instructor:Cv.get("helpSiteUrl")+"/help/cv/pm-help-instructor.html",student:Cv.get("helpSiteUrl")+"/help/cv/pm-help-student.html"}),3:SC.Object.create({instructor:Cv.get("helpSiteUrl")+"/help/cv/gm-help-instructor.html",student:Cv.get("helpSiteUrl")+"/help/cv/gm-help-student.html"})}),action:function(){var d=Cv.servicesController.getPath("activeService.id")||0;
var c=(Cv.get("inStudentMode")?"student":"instructor");var b=this.getPath("urls."+d+"."+c)+"?lang="+Cv.get("lang");
if(b){window.open(b,"_blank","width=1216,scrollbars=yes")}}}),navigationView:SC.View.design(SCUI.ToolTip,{childViews:"previousButtonView paperStubSelectorView demoPaperStubSelectorView nextButtonView".w(),assignmentBinding:SC.Binding.oneWay("Cv.assignmentController.content"),notStudentBinding:SC.Binding.not("Cv.inStudentMode").bool().oneWay(),assignmentOverPaperLimitBinding:SC.Binding.oneWay("Cv.assignmentController.overPaperSizeLimit"),hidePaperNavigationBinding:SC.Binding.oneWay("Cv.classController.hidePaperNavigation"),isVisible:function(){if(Cv.config.get("HIDE_PAPER_NAVIGATION")){return NO
}if(!this.get("assignment")){return NO}var c=this.get("notStudent");var d=this.get("assignmentOverPaperLimit");
var b=this.get("hidePaperNavigation");return(c&&!d&&!b)}.property("assignment","notStudent","assignmentOverPaperLimit","hidePaperNavigation").cacheable(),layout:{top:0,right:0,width:190},toolTip:"_Navigate to other submissions for this assignment".loc(),previousButtonView:SC.ButtonView.design({layout:{top:0,bottom:0,left:0,width:20},classNames:["navbar-left-arrow"],previousPaperBinding:"Cv.paperStubsController.previousStub",action:function(){if(Cv.demoNotice()){return
}var b={fn:function(c){Cv.paperStubsController.selectPrevious()},target:this,args:arguments};
if(Cv.editingRegistryController.tryToPerform(b)){_gaq.push(["_trackEvent",Cv.GA.CATEGORY_PAPER_NAV,Cv.GA.ACTION_PREVIOUS,Cv.GA.getSessionUUID()])
}},isEnabled:function(){return !!this.get("previousPaper")}.property("previousPaper").cacheable()}),nextButtonView:SC.ButtonView.design({layout:{top:0,bottom:0,right:0,width:20},classNames:["navbar-right-arrow"],nextPaperBinding:"Cv.paperStubsController.nextStub",action:function(){if(Cv.demoNotice()){return
}var b={fn:function(c){Cv.paperStubsController.selectNext()},target:this,args:arguments};
if(Cv.editingRegistryController.tryToPerform(b)){_gaq.push(["_trackEvent",Cv.GA.CATEGORY_PAPER_NAV,Cv.GA.ACTION_NEXT,Cv.GA.getSessionUUID()])
}},isEnabled:function(){return !!this.get("nextPaper")}.property("nextPaper").cacheable()}),demoPaperStubSelectorView:SC.ButtonView.design({layout:{top:0,bottom:0,centerX:0,width:130},classNames:["assignment-number"],isEnabledBinding:SC.Binding.bool("Cv.inDemoMode"),isVisibleBinding:SC.Binding.bool("Cv.inDemoMode"),title:"_Paper %@ of %@".loc(1,1),action:function(){SC.PickerPane.create({layout:{width:250,height:50},contentView:SC.LabelView.extend({classNames:"demo-paper-select-notice",autoResizeLayer:YES,value:"_Student submissions in your assignment will be listed here".loc()})}).popup(this)
}}),paperStubSelectorView:Cv.SelectView.design({layout:{top:0,bottom:0,centerX:0,width:130},classNames:"assignment-number",itemsLengthBinding:"Cv.paperStubsController.length",itemsBinding:"Cv.paperStubsController.arrangedObjects",itemTitleKey:"listingDisplay",valueBinding:"Cv.paperStubsController.selectedStub",isEnabledBinding:SC.Binding.bool(".itemsLength"),lastMenuWidth:225,positionMenuBelow:YES,displayProperties:["displayTitle","items","value"],isVisibleBinding:SC.Binding.bool("Cv.inDemoMode").not(),displayTitle:function(){var c=this.get("itemsLength");
var e=this.get("value");var b=e?this.get("items").indexOf(e)+1:"--";var d="_Paper %@ of %@".loc(b,c);
return d}.property("value","items","itemsLength").cacheable(),displaySelectedItem:function(){if(Cv.demoNotice()){return
}var b={fn:function(c){c.callee.base.apply(this,c);_gaq.push(["_trackEvent",Cv.GA.CATEGORY_PAPER_NAV,Cv.GA.ACTION_MENU_SELECTED,Cv.GA.getSessionUUID()])
},target:this,args:arguments};Cv.editingRegistryController.tryToPerform(b)}})})});
return a},_createInfoBarViewDesign:function(){var a=SC.View.design({layout:{top:20,left:0,height:60,minWidth:800},classNames:["infobar"],childViews:"applicationSelectorView paperInfoView brandingView similarityScoreView gradeView".w(),applicationSelectorView:Cv.ApplicationSelectorView,paperInfoView:SC.View.design({layout:function(){var b=345-(Cv.config.get("HIDE_BRANDING")?152:0);
var c=330-(Cv.config.get("HIDE_BRANDING")?150:0);return{top:0,height:60,left:c,right:b}
}.property().cacheable(),childViews:"paperTitleView authorView".w(),classNames:["infobar-paper-info"],paperTitleView:SC.LabelView.design({layout:{top:10,height:24,left:0,right:0},textAlign:SC.ALIGN_CENTER,classNames:["infobar-title"],valueBinding:"Cv.paperController.title"}),authorView:SC.LabelView.design({layout:{top:35,left:0,right:0},classNames:["author"],textAlign:SC.ALIGN_CENTER,escapeHTML:NO,selectedStubBinding:"Cv.paperStubController.content",authorFullNameBinding:"Cv.paperAuthorController.fullName",authorEmailBinding:"Cv.paperAuthorController.email",anonymousMarkingIsActiveBinding:"Cv.assignmentController.anonymousMarkingIsActive",isAnonymousExemptBinding:"Cv.paperController.isAnonymousExempt",authorFullNameHyperlinked:function(){var b=this.get("authorFullName");
var c=this.get("authorEmail");if(c&&b){return['<a class="author-email" href="mailto:',c,'">',b,"</a>"].join("")
}else{return null}}.property("authorFullName").cacheable(),value:function(){var d;
if(Cv.get("inStudentMode")){d="_by %@".loc(Cv.userController.get("fullName"))}else{if(Cv.config.HIDE_STUDENT_EMAIL){d="_by %@".loc(this.get("authorFullName"))
}else{var b=this.get("authorFullNameHyperlinked");if(b){d="_by %@".loc(b)}else{var c=this.get("selectedStub");
if(c){d="_by %@".loc(c.get("authorFullName"))}}}}return d}.property("authorFullNameHyperlinked","selectedStub","isAnonymousExempt").cacheable(),mouseDown:function(){if(this.get("anonymousMarkingIsActive")&&!this.get("isAnonymousExempt")){this.get("exemptAnonymityPane").append()
}return NO},exemptAnonymityPane:function(){var b=SC.PanelPane.create({layout:{height:340,width:500,centerX:0,centerY:0},classNames:["modal-dialog"],contentView:SC.View.design({layout:{top:0,right:0,bottom:0,left:0},childViews:"headingLabel messageLabel reasonTextarea divider submitButton closeButton".w(),headingLabel:SC.LabelView.design({layout:{top:20,right:20,height:20,left:20},classNames:["modal-heading"],value:"_Reveal Author Identity".loc(),isEditable:NO}),messageLabel:SC.LabelView.design({layout:{top:55,right:20,height:30,left:20},value:"_Please provide a reason to reveal the author's identity".loc(),isEditable:NO}),reasonTextarea:SC.TextFieldView.design({layout:{height:170,right:20,top:92,left:20},classNames:["modal-body"],hint:"_Reason...".loc(),isPassword:YES,isTextArea:YES}),divider:SC.LabelView.design({layout:{bottom:52,right:20,height:0,left:20},classNames:["modal-divider"]}),submitButton:SC.ButtonView.design({layout:{height:30,right:150,bottom:13,width:110},classNames:["panel-button","primary"],title:"_Submit".loc(),reasonBinding:".parentView.reasonTextarea.value",selectedStubBinding:"Cv.paperStubsController.selectedStub",isEnabled:function(){return this.get("reason")&&this.get("reason").length>5
}.property("reason").cacheable(),action:"deanonymize",target:"Cv.paperController"}),closeButton:SC.ButtonView.design({layout:{height:30,right:20,bottom:13,width:110},classNames:["panel-button"],isCancel:YES,title:"_Cancel".loc(),action:function(){this.get("pane").remove()
}})})});return b}.property().cacheable()})}),brandingView:SC.View.design({layout:function(){return{top:0,width:150,right:(this.get("similarityIndexIsVisible")?193:81)}
}.property("similarityIndexIsVisible").cacheable(),childViews:"logoView".w(),classNames:["branding-view"],similarityIndexIsVisibleBinding:SC.Binding.oneWay("Cv.originalityController.isApplicable").bool(),isVisibleBinding:SC.Binding.not("Cv.config.HIDE_BRANDING"),logoView:Ip.ImageView.design({layout:{top:16,height:32,centerX:0,width:115},value:"https://www.turnitincdn.com/800404/static.turnitin.com/cv/20141205.1016/cv/en_us/A/resources/images/tii-logo.png"})}),similarityScoreView:Cv.InfoTileView.design({layout:{top:0,right:91,width:100},classNames:["similarity-view"],isVisibleBinding:SC.Binding.oneWay("Cv.originalityController.isApplicable").bool(),toolTip:function(){var c="_Percent of submission that matches selected Turnitin sources".loc(),f=this.get("originalityIsAvailable"),e=this.get("originalityIsApplicable"),h=this.get("isAnythingSubmission"),d=this.get("isImageFileSubmission"),b=this.get("reportNotGenerating"),g=this.get("isNothingSubmission");
if(!f){if(e){if(g){c="_OriginalityCheck is not available because no file was submitted.".loc()
}else{if(h||d||b){c="_OriginalityCheck isn't available for this submission because %@ could not extract enough text to generate an Originality Report.".loc(Cv.config.get("APP_NAME"))
}else{c="_The Originality Report is not done generating for this submission.".loc(Cv.config.get("APP_NAME"))
}}}else{c="_The Originality Report is not available for this submission.".loc()}}return c
}.property("originalityIsApplicable","originalityIsAvailable","isImageFileSubmission","isAnythingSubmission","reportNotGenerating","isNothingSubmission").cacheable(),originalityIsAvailableBinding:SC.Binding.oneWay("Cv.originalityController.isAvailable"),originalityIsApplicableBinding:SC.Binding.oneWay("Cv.originalityController.isApplicable"),isAnythingSubmissionBinding:SC.Binding.oneWay("Cv.paperController.isAnythingSubmission"),isImageFileSubmissionBinding:SC.Binding.oneWay("Cv.paperController.isImageFileSubmission"),isNothingSubmissionBinding:SC.Binding.oneWay("Cv.paperController.isNothingSubmission"),reportNotGeneratingBinding:SC.Binding.oneWay("Cv.paperController.reportNotGenerating"),translateLanguageBinding:"Cv.originalityController.translateLanguage",topLabel:function(){var b;
if(Cv.translatedMatchingController.isEnglish()){b='<span class="translated-report-indicator">EN (Beta)</span>'
}return b}.property("translateLanguage").cacheable(),topToolTip:function(){var b;
if(Cv.translatedMatchingController.isEnglish()){b="_This is the percentage of the English translation of this paper that was found to match English language sources in the Turnitin databases.".loc()
}return b}.property("translateLanguage").cacheable(),bottomLabel:"_Similar".loc(),percentBinding:"Cv.similarityScoreController.displayPercent",mainContent:function(){var b=this.get("percent");
if(Cv.get("inDemoMode")){b=10}var c="_%@%".loc(b);return c}.property("percent").cacheable()}),gradeView:SC.View.design(SCUI.ToolTip,{layout:{top:0,right:10,width:80},childViews:"gradeValueView maxPointsView".w(),classNames:["grade-view"],isVisibleBinding:SC.Binding.not("Cv.config.HIDE_GRADE_BOX"),toolTip:!Cv.get("inStudentMode")?"_Edit grade for this paper".loc():null,gradeValueView:SC.LabelView.design({layout:{top:13,height:26,centerX:0,width:50},textAlign:SC.ALIGN_CENTER,classNames:["infobar-value","grade"],paperBinding:"Cv.paperController.content",assignmentController:this.get("assignmentController"),render:function(d,h){arguments.callee.base.apply(this,arguments);
var f=this.get("value");var b=30;var c='font-family: "Helvetica Neue",Helvetica,Verdana,Arial,sans-serif;';
var g=this.get("layout").width;if(f&&f.toString().length>3){var e="font-size: "+b+"px; "+c;
while(b>12&&Ip.metricsForString(f,e).width>g){b-=4;e="font-size: "+b+"px; "+c}}d.addStyle({"font-size":b+"px"})
},validator:SC.Validator.Number,isEditable:function(){var b=NO;var c=this.get("paper");
if(!Cv.get("inStudentMode")&&c&&!c.get("isReadonly")&&this.get("gradebookIsActive")){b=YES
}return b}.property("paper","gradebookIsActive").cacheable(),gradebookIsActiveBinding:"Cv.classController.gradebookProductIsActive",valueBinding:SC.Binding.notEmpty("Cv.paperController.grade","--".loc()),exampleInlineTextFieldView:SC.InlineTextFieldView.extend({classNames:["grade-view"],getValidatedValueFromFieldValue:function(b){var d=this.getFieldValue();
if(!b){var c=parseInt(d,10);if(c!=d){c=""}}else{c=d}return c},keyUp:function(b){var c=this.interpretKeyEvents(b);
this.fieldValueDidChange(true);return !c?NO:c},didLoseKeyResponderTo:function(b){if(this.$input()[0]){arguments.callee.base.apply(this,arguments)
}}}),click:function(b){Cv.servicesController.readonlyAlert();return this.beginEditing()
},inlineEditorDidEndEditing:function(b,c){this.invokeLast(function(){Cv.paperController.saveGrade()
});return arguments.callee.base.apply(this,arguments)}}),maxPointsView:SC.LabelView.design({layout:{bottom:0,left:0,right:0,height:16},classNames:["label"],assignmentController:this.get("assignmentController"),maxPointsBinding:SC.Binding.oneWay(".assignmentController.maxPoints"),textAlign:SC.ALIGN_CENTER,value:function(){var b=this.getPath("maxPoints");
var c=("_out of %@".loc(b));return c}.property("maxPoints").cacheable()})})});return a
},_createToolbarViewDesign:function(){var a=SC.View.design({});return a},_createSplitViewDesign:function(){var a=Cv.ApplicationSplitView.design({layout:{top:81,left:0,right:0},_sidebarvisibilityDidChange:function(){if(this.get("sidebarIsVisible")){this.getPath("topLeftView.toolbarView.pageSelectorView").adjust("right",245);
this.getPath("topLeftView.toolbarView.zoomControlsView").adjust("right",50)}else{this.getPath("topLeftView.toolbarView.pageSelectorView").adjust("right",525);
this.getPath("topLeftView.toolbarView.zoomControlsView").adjust("right",330)}arguments.callee.base.apply(this,arguments)
}.observes("sidebarIsVisible","sidebarIsWider"),topLeftView:SC.View.design(SC.Animatable,{childViews:"paperView readOnlyBannerView toolbarView statusMessagingView".w(),classNames:["paper-wrapper-view"],transitions:{right:{duration:0.15,timing:SC.TRANSITION_CSS_EASE}},paperView:Cv.PaperView.design({layout:{top:0,bottom:30,left:10,right:0},classNames:["paper-view"],paperBinding:"Cv.paperController",nowShowingPageBinding:"Cv.paperController.nowShowingPage",paperTextSelectionController:this.get("paperTextSelectionController"),servicesController:this.get("servicesController"),zoomController:this.get("zoomController")}),readOnlyBannerView:SC.LabelView.design({layout:{top:15,right:30,height:30,width:100},classNames:["read-only-banner"],value:"_Read only".loc(),isStudentBinding:"Cv.inStudentMode",isReadonlyBinding:"Cv.paperController.isReadonly",isVisible:function(){var c=this.get("isStudent");
var b=this.get("isReadonly");return !c&&b}.property("isStudent","isReadonly").cacheable()}).loc(Ip.getLocalizationHash("Cv.readOnlyBanner")),statusMessagingView:SC.View.design({layout:{height:24,right:14,bottom:30,width:185},childViews:"messageView spinnerView".w(),backgroundColor:"black",eRaterReadIsLoadingBinding:"Cv.eRaterReadQueryController.isLoading",eRaterReadBinding:"Cv.eRaterReadController.content",eRaterReadIsHiddenBinding:"Cv.eRaterReadController.isHidden",eRaterReadIsCorruptedBinding:"Cv.eRaterReadController.isCorrupted",paperBinding:"Cv.paperController.content",isVisible:function(){var e=this.get("eRaterReadIsLoading");
var f=this.get("eRaterRead");var c=this.get("eRaterReadIsHidden");var d=this.get("eRaterReadIsCorrupted");
var g=this.getPath("paper.dprPreWithImageDimensions");var b=(e||(f&&c&&!d&&!g));return b
}.property("eRaterReadIsLoading","eRaterRead","eRaterReadIsHidden","eRaterReadIsCorrupted").cacheable(),messageView:SC.LabelView.design({layout:{centerY:0,left:25,height:20},escapeHTML:NO,value:"_ETS&reg; Data Loading...".loc()}).loc(Ip.getLocalizationHash("Cv.loadingLabel")),spinnerView:SC.View.design({layout:{centerY:0,left:5,height:16,width:16},render:function(d,g){var f=this.get("frame");
var e=f.width;var b=f.height;var c="https://www.turnitincdn.com/800404/static.turnitin.com/cv/20141205.1016/ip/en_us/A/resources/loading-spinner.gif";
d.push('<img src="%@" width="%@" height="%@">'.fmt(c,e,b))}})}),toolbarView:SC.View.design({childViews:"paperInfoButtonView classAccessCodeButtonView printDownloadButtonsView printDownloadMenuView printDownloadSpinnerView undoButtonView pageSelectorView zoomControlsView classicReportButtonView hideSidebarButtonView".w(),layout:{bottom:0,height:30,left:0,right:0,minWidth:500},classNames:["paper-toolbar"],paperInfoButtonView:SC.ButtonView.design({layout:{centerY:0,height:28,left:10,width:34},classNames:["paper-info-button"],paperController:this.get("paperController"),paperBinding:"Cv.paperController.content",translateLanguageBinding:"Cv.originalityController.translateLanguage",commentCountBinding:"Cv.markSetController.commentAndInlineCount",quickMarkCountBinding:"Cv.markSetController.quickMarkCount",toolTip:"_View information about this paper".loc(),icon:"https://www.turnitincdn.com/800404/static.turnitin.com/cv/20141205.1016/cv/en_us/A/resources/images/footer-button-info.png",titleMinWidth:"32px",action:function(){this.get("infoPane").popup(this)
},infoPane:function(){var f=this.get("paper");var b=Cv.classController.get("displayTimeIn24Hr")?"__ipDefaultFullDateTime24HrFormat".loc():"__ipDefaultFullDateTimeFormat".loc();
var e=f.get("uploadedDate")?f.get("uploadedDate").toFormattedString(b):"_N/A".loc();
var c=SC.none(this.get("commentCount"))?f.get("gradeMarkCommentCount"):this.get("commentCount");
var d=SC.none(this.get("quickMarkCount"))?f.get("gradeMarkQuickMarkCount"):this.get("quickMarkCount");
var g=SC.PickerPane.design({classNames:["footer-info-pane","paper-info-pane"],layout:{bottom:35,left:10,width:350},isModal:YES,isAnchored:YES,render:function(h,i){if(h.needsContent){this.renderChildViews(h,i)
}},didAppendToDocument:function(){var h=this.get("height"),i=this.$(".inner-container")[0].offsetHeight+40;
if(h!==i){this.adjust("height",i);this.positionPane()}},contentView:SC.View.design({classNames:["footer-info-content","paper-info-content"],render:function(k,o){k.push("<h1>").push("_Submission Info".loc()).push("</h1>");
k.push('<div class="inner-container">');k.push("<div>").push("<span>").push(f.get("id")).push("</span>").push("_SUBMISSION ID".loc()).push("</div>");
k.push("<div>").push('<span class="infopane-date">').push(e).push("</span>").push("_SUBMISSION DATE".loc()).push("</div>");
k.push("<div>").push("<span>").push(f.get("submissions")).push("</span>").push("_SUBMISSION COUNT".loc()).push("</div>");
if(!f.get("isNothingSubmission")){k.push("<div>").push('<span class="ellipsis">').text(f.get("fileName")).push("</span>").push("_FILE NAME".loc()).push("</div>");
if(f.get("fileSize")){k.push("<div>").push("<span>").push(f.get("fileSize")).push("</span>").push("_FILE SIZE".loc()).push("</div>")
}if(!f.get("isAnythingSubmission")&&!f.get("isNothingSubmission")){k.push("<div>").push("<span>").push(f.get("characterCount")).push("</span>").push("_CHARACTER COUNT".loc()).push("</div>");
k.push("<div>").push("<span>").push(f.get("wordCount")).push("</span>").push("_WORD COUNT".loc()).push("</div>");
k.push("<div>").push("<span>").push(f.get("pageCount")).push("</span>").push("_PAGE COUNT".loc()).push("</div>")
}}if(!Cv.get("inStudentMode")||Cv.assignmentController.get("studentsCanViewReports")){if(Cv.originalityController.get("isAvailable")||Cv.get("inDemoMode")){k.push("<h2>");
if(Cv.translatedMatchingController.isEnglish()){k.push('<span class="translated-report-indicator">').push("EN").push("</span> ")
}k.push("_Originality".loc()).push("</h2>");var i;var n;var m;var l;if(Cv.get("inDemoMode")){i=10;
n=6;m=4;l=0}else{if(Cv.translatedMatchingController.isNative()){i=f.get("overlap");
n=f.get("internetOverlap");m=f.get("publicationsOverlap");l=f.get("submittedWorksOverlap")
}else{i=f.get("translateOverlap");n=f.get("translateInternetOverlap");m=f.get("translatePublicationsOverlap");
l=f.get("translateSubmittedWorksOverlap")}}n=(n===null)?"_N/A".loc():"_%@%".loc(n);
m=(m===null)?"_N/A".loc():"_%@%".loc(m);l=(l===null)?"_N/A".loc():"_%@%".loc(l);k.push("<div>").push("<span>").push("_%@%".loc(i)).push("</span>").push("_OVERALL".loc()).push("</div>");
k.push('<div class="child">').push("<span>").push(n).push("</span>").push("_INTERNET".loc()).push("</div>");
k.push('<div class="child">').push("<span>").push(m).push("</span>").push("_PUBLICATIONS".loc()).push("</div>");
k.push('<div class="child">').push("<span>").push(l).push("</span>").push("_STUDENT PAPERS".loc()).push("</div>")
}}if(!Cv.get("inStudentMode")||SC.DateTime.compare(SC.DateTime.create(),Cv.assignmentController.get("postDate"))){if(!Cv.gradeMarkController.get("isHiddenByConfig")&&Cv.gradeMarkController.get("isAvailable")){var h="__ipDefaultFullDateFormat".loc();
var j=f.get("gradeMarkLastSaved")?f.get("gradeMarkLastSaved").toFormattedString(h):"_N/A".loc();
k.push("<h2>").push("_GradeMark".loc()).push("</h2>");k.push("<div>").push('<span class="infopane-date">').push(j).push("</span>").push("_LAST GRADED".loc()).push("</div>");
k.push("<div>").push("<span>").push(c).push("</span>").push("_COMMENTS".loc()).push("</div>");
k.push("<div>").push("<span>").push(d).push("</span>").push("_QUICKMARKS".loc()).push("</div>")
}}k.push("</div>")}})}).loc(Ip.getLocalizationHash("Cv.paperInfoPane"));return g.create({})
}.property("paper","translateLanguage","commentCount","quickMarkCount").cacheable()}),classCanGenerateIPadAccessCode:NO,classCanGenerateIPadAccessCodeBinding:"Cv.classController.canGenerateIPadAccessCode",classAccessCodeButtonIsVisible:function(){var b=this.get("classCanGenerateIPadAccessCode");
var c=Cv.get("inStudentMode");return b&&Cv.config.get("SHOW_IPAD_CLASS_ACCESS_CODE_LINK")&&!c
}.property("classCanGenerateIPadAccessCode").cacheable(),classAccessCodeButtonView:SC.ButtonView.design({layout:{centerY:0,height:28,left:50,width:34},classNames:["class=access-code-button"],isVisibleBinding:".parentView.classAccessCodeButtonIsVisible",icon:"https://www.turnitincdn.com/800404/static.turnitin.com/cv/20141205.1016/cv/en_us/A/resources/images/footer-button-ipad.png",toolTip:"_Get class access code for iPad app".loc(),titleMinWidth:"32px",action:function(){this.get("classAccessCodePane").popup(this)
},classAccessCodePane:function(){var b=SC.PickerPane.create({classNames:["footer-info-pane","ipad-class-access-code-pane"],layout:{height:240,width:320},isModal:YES,contentView:SC.View.extend({classNames:"footer-info-content".w(),childViews:"generateCodeButtonView loadingView codeLabelView".w(),codeIsLoading:NO,codeIsLoaded:NO,code:null,generateCodeButtonView:SC.ButtonView.design({layout:{width:286,height:30,centerX:0,bottom:30},classNames:["panel-button","primary"],codeIsLoadingBinding:".parentView.codeIsLoading",codeIsLoadedBinding:".parentView.codeIsLoaded",isVisible:function(){var d=this.get("codeIsLoading");
var e=this.get("codeIsLoaded");var c=!d&&!e;return c}.property("codeIsLoading","codeIsLoading").cacheable(),title:"_Generate code".loc(),action:function(){if(Cv.classController.get("isExpired")){SC.AlertPane.info("_Read Only".loc(),"_A class access code cannot be generated for this class because the class has expired and is now read-only.".loc(),null,"_OK".loc());
return}this.set("codeIsLoading",YES);this.set("codeIsLoaded",NO);var d=this.get("parentView");
var c=Ip.LocalizedUrl.prepareUrl("/class/"+Cv.classController.get("id")+"/generate_ipad_access_code");
Ip.TransientRequest.executeTransientGet(c,{successCallback:function(f){var e=f.code;
d.set("code",e);d.set("codeIsLoading",NO);d.set("codeIsLoaded",YES)},failureCallback:function(g,e,f){d.set("codeIsLoading",NO);
d.set("codeIsLoaded",NO);SC.AlertPane.error("_Error".loc(),"_There was an error generating the class access code.".loc(),e+": "+f.get("message"),"_OK".loc())
}})}}),loadingView:Ip.LoadingView.extend({layout:{height:30,bottom:30,left:10,right:10},isVisibleBinding:".parentView.codeIsLoading"}),codeLabelView:SC.TextFieldView.design({layout:{height:38,bottom:30,left:15,right:15},classNames:"code-label-view".w(),textAlign:SC.ALIGN_CENTER,controlSize:SC.LARGE_CONTROL_SIZE,maxLength:19,isEditable:NO,isVisible:NO,isVisibleBinding:".parentView.codeIsLoaded",codeBinding:".parentView.code",value:function(){var e="";
var d=this.get("code");if(d){var c=new Array();while(d.length!=0){c.push(d.substring(0,4));
d=d.substring(4)}e=c.join(" ")}return e}.property("code").cacheable(),_prevIsVisible:NO,isVisibleDidChange:function(){var c=this.get("isVisible");
if(!this._prevIsVisible&&c){var d=this.$("input")[0];this.invokeLater(function(){d.focus();
d.select()},50)}}.observes("isVisible")}),render:function(c,d){c.push("<h1>").push("_Turnitin for iPad&reg; Class Access Code".loc()).push("</h1>");
c.push('<div class="inner-container" style="height: 200px">');c.push("<div>").push("<span>");
c.push("_You will need this code to access your class through the Turnitin iPad app.".loc());
c.push("</span>").push("</div>");c.push("<div>").push("<span>");c.push("_Please return here if you ever need to generate a new class access code.".loc());
c.push("</span>").push("</div>");return arguments.callee.base.apply(this,arguments)
}})});return b}.property("paper","translateLanguage","commentCount","quickMarkCount").cacheable()}),printDownloadButtonsView:SC.SegmentedView.design(SCUI.ToolTip,{classAccessCodeButtonIsVisible:NO,classAccessCodeButtonIsVisibleBinding:".parentView.classAccessCodeButtonIsVisible",layout:function(){var b={centerY:0,height:28,left:50,width:100};
if(this.getPath("parentView.classAccessCodeButtonIsVisible")){b.left+=40}return b
}.property("classAccessCodeButtonIsVisible").cacheable(),classNames:["print-download-buttons"],toolTip:"_Print / Download".loc(),isEnabledBinding:"Cv.paperController.content",isVisibleBinding:SC.Binding.not("Cv.config.CAN_DOWNLOAD_DIGITAL_RECEIPT"),itemWidthKey:"width",itemIsEnabledKey:"isEnabled",itemIconKey:"icon",itemActionKey:"action",itemTargetKey:"target",itemTitleKey:"title",items:[{isEnabled:YES,width:35,icon:"https://www.turnitincdn.com/800404/static.turnitin.com/cv/20141205.1016/dv/en_us/A/resources/images/legacy-footer-button-print.png",title:"",action:"printPaper",target:"Cv.printController"},{isEnabled:YES,width:35,icon:"https://www.turnitincdn.com/800404/static.turnitin.com/cv/20141205.1016/dv/en_us/A/resources/images/legacy-footer-button-download.png",title:"",action:"downloadPaper",target:"Cv.printController"}]}),printDownloadMenuView:SC.ButtonView.design(SCUI.ToolTip,{classAccessCodeButtonIsVisible:NO,classAccessCodeButtonIsVisibleBinding:".parentView.classAccessCodeButtonIsVisible",layout:function(){var b={centerY:0,height:28,left:50,width:50,minWidth:0};
if(this.getPath("parentView.classAccessCodeButtonIsVisible")){b.left+=40}return b
}.property("classAccessCodeButtonIsVisible").cacheable(),classNames:["print-download-menu-button"],paperController:this.get("paperController"),paperBinding:"Cv.paperController.content",isEnabledBinding:"Cv.paperController.content",isVisibleBinding:"Cv.config.CAN_DOWNLOAD_DIGITAL_RECEIPT",toolTip:"_Print / Download".loc(),icon:"https://www.turnitincdn.com/800404/static.turnitin.com/cv/20141205.1016/dv/en_us/A/resources/images/legacy-footer-button-print.png",title:null,titleMinWidth:0,printDownloadIsLoadingBinding:"Cv.printController.printDownloadIsLoading",printDownloadTimer:null,action:function(){this.get("menuPane").popup(this,SC.PICKER_MENU)
},menuPane:function(){var b=SC.MenuPane.design({layout:{width:300,bottom:0,height:50},itemIsEnabledKey:"isEnabled",itemActionKey:"action",itemTargetKey:"target",itemTitleKey:"title",itemHeightKey:"height",itemOptionsKey:"options",items:[{isEnabledBinding:SC.Binding.oneWay("Cv.printController.printDownloadIsLoading").bool().not(),height:20,title:"_Download PDF of current view for printing".loc(),action:"printPaper",target:"Cv.printController"},{isEnabledBinding:SC.Binding.oneWay("Cv.printController.receiptDownloadEnabled").bool(),height:20,title:"_Download PDF of digital receipt for printing".loc(),action:"downloadReceipt",target:"Cv.printController"},{hasSubmissionUrlBinding:SC.Binding.oneWay("Cv.paperController.submissionUrl").bool(),mayDownloadOriginalSubmissionBinding:SC.Binding.oneWay("Cv.paperController.mayDownloadOriginalSubmission"),isEnabled:function(){return this.get("hasSubmissionUrl")&&this.get("mayDownloadOriginalSubmission")
}.property("hasSubmissionUrl","mayDownloadOriginalSubmission").cacheable(),height:20,title:"_Download submitted file".loc(),action:"downloadOriginalSubmission",target:"Cv.paperController"}]});
return b.create({})}.property().cacheable()}),printDownloadSpinnerView:SC.View.design({classAccessCodeButtonIsVisible:NO,classAccessCodeButtonIsVisibleBinding:".parentView.classAccessCodeButtonIsVisible",layout:function(){var b={centerY:0,left:110,height:16,width:16};
if(this.getPath("parentView.classAccessCodeButtonIsVisible")){b.left+=40}return b
}.property("classAccessCodeButtonIsVisible").cacheable(),isVisibleBinding:SC.Binding.oneWay("Cv.printController.printDownloadIsLoading"),render:function(d,g){var f=this.get("frame");
var e=f.width;var b=f.height;var c="https://www.turnitincdn.com/800404/static.turnitin.com/cv/20141205.1016/ip/en_us/A/resources/loading-spinner.gif";
d.push('<img src="%@" width="%@" height="%@">'.fmt(c,e,b))}}),undoButtonView:SC.SegmentedView.design({classAccessCodeButtonIsVisible:NO,classAccessCodeButtonIsVisibleBinding:".parentView.classAccessCodeButtonIsVisible",layout:function(){var b={centerY:0,height:28,left:110,width:270};
if(Cv.config.get("CAN_DOWNLOAD_DIGITAL_RECEIPT")){b.left+=30}if(this.getPath("parentView.classAccessCodeButtonIsVisible")){b.left+=40
}return b}.property("classAccessCodeButtonIsVisible").cacheable(),classNames:["undo-button"],itemTitleKey:"title",itemTargetKey:"target",itemActionKey:"action",isVisibleBinding:SC.Binding.notEmpty("Cv.undoController.content",NO),items:function(){var b=[];
if(this.get("isVisible")){if(Cv.undoController.get("deletedMarkType")){var c="_"+Cv.undoController.get("deletedMarkType")+" has been deleted";
b.push({title:c.loc(),target:"Cv.undoController",action:"undoLastChange"})}b.push({title:"_Undo".loc(),target:"Cv.undoController",action:"undoLastChange"})
}return b}.property("isVisible").cacheable()}),pageSelectorView:SC.View.design(SC.Animatable,{layout:{centerY:0,height:20,right:225,width:90},transitions:{right:{duration:0.15,timing:SC.TRANSITION_CSS_EASE}},childViews:"pageLabelView selectButtonView pageCountView".w(),pageLabelView:SC.LabelView.design({classNames:["page-label"],layout:{top:0,centerY:0,left:0,width:40},textAlign:SC.ALIGN_RIGHT,value:"_Page:".loc()}),selectButtonView:SC.LabelView.design({layout:{centerY:0,right:37,top:0,width:15},textAlign:SC.ALIGN_RIGHT,layerId:"current_page_number",paperController:this.get("paperController"),valueBinding:"Cv.paperController.nowShowingPage",paperViewBinding:SC.Binding.oneWay(".parentView.parentView.parentView.paperView"),scrollPaperView:function(){if(!this.getPath("paperView.paper")){return
}var c=this.get("itemIdx");var e=this.getPath("paperView.pageListView");var d=this.get("objects").objectAt(c).get("number");
var b=e.get("nowShowingPage");if(d!==b){this.invokeLast(function(){var f=e.itemViewForContentIndex(c);
f.scrollToVisible()})}}.observes("itemIdx")}),pageCountView:SC.LabelView.design({layout:{top:0,centerY:0,right:0,width:35},pageCountBinding:SC.Binding.notEmpty("Cv.paperController.pageCount","--"),value:function(){return"_of %@".loc(this.getPath("pageCount"))
}.property("pageCount").cacheable()})}),zoomControlsView:Cv.ZoomControlsView.design({layout:{top:0,bottom:0,right:40,width:165},paperViewBinding:SC.Binding.oneWay(".parentView.parentView.paperView")}),classicReportButtonView:SC.ButtonView.design({init:function(){arguments.callee.base.apply(this,arguments);
var b={right:30,width:120,height:24,bottom:0};this.set("layout",b)},classNames:["or-olde-version","olde-version"],title:"_Text-Only Report".loc(),action:function(){var b=Cv.get("lang");
window.location="/newreport.asp?lang=%@&oid=%@&ft=1&bypass_cv=1".fmt(b,Cv.paperController.get("id"))
},target:this,toolTip:"_Navigate to text-only Originality Report".loc(),sidebarIsVisibleBinding:SC.Binding.oneWay(".parentView.parentView.parentView.sidebarIsVisible"),servicesController:this.get("servicesController"),originalityIsActiveBinding:SC.Binding.transform(function(b){return(b)?(b.id===1?YES:NO):NO
}).from(".servicesController.activeService"),isDemoModeBinding:SC.Binding.transform(function(b){return(b)?(b===1?YES:NO):NO
}).from("Cv.inDemoMode"),isVisible:function(){return(this.get("originalityIsActive")&&!this.get("sidebarIsVisible"))
}.property("originalityIsActive","sidebarIsVisible").cacheable()}),hideSidebarButtonView:SC.ButtonView.design(SCUI.ToolTip,{layout:{width:13,right:0,bottom:0,height:30},target:"parentView.parentView.parentView",action:"toggleSidebarVisibility",isEnabledBinding:SC.Binding.not("Cv.recordingController.isRecording"),sidebarIsVisibleBinding:".parentView.parentView.parentView.sidebarIsVisible",visibilityDidChange:function(){var b=this.get("classNames").concat();
if(this.get("sidebarIsVisible")){b.removeObject("show-sidebar");b.push("hide-sidebar")
}else{b.removeObject("hide-sidebar");b.push("show-sidebar")}this.set("classNames",b);
this.set("toolTip",this.get("sidebarIsVisible")?"_Hide sidebar".loc():"_Show sidebar".loc())
}.observes("sidebarIsVisible")})})}),bottomRightView:SC.ContainerView.design(SC.Animatable,{servicesController:this.get("servicesController"),activeServiceBinding:SC.Binding.oneWay(".servicesController.activeService"),transitions:{right:{duration:0.15,timing:SC.TRANSITION_CSS_EASE}},updateSidebarView:function(){var b=this.get("activeService");
if(b){this.set("contentView",b.get("sidebarView"))}else{this.set("contentView",SC.View.create({layout:{top:0,bottom:0,left:0,right:0},childViews:"noServiceView footerView".w(),noServiceView:SC.LabelView.design({layout:{centerX:0,centerY:0,width:200,height:40},value:"_No Service Currently Active".loc()}),footerView:SC.View.design({layout:{left:0,right:0,bottom:0,height:30},classNames:"sidebar-footer"})}))
}this.setPath("parentView.sidebarIsWider",NO)}.observes("activeService")})});return a
}});Dv.mainPage=SC.Page.design({mainPane:SC.MainPane.design({childViews:"screenReaderLinkView applicationView loadingView audioPlayerSwfView".w(),defaultResponder:"Cv.paperView",bypassFirstTimeMessageBinding:SC.Binding.bool("Cv.userController.bypassFirstTimeMessage"),firstTimeMessageDisplayed:NO,classProductsBinding:"Cv.classController.productStatus",screenReaderLinkView:Ip.AnchorTagView.design({layout:{height:0},classNames:["skip-nav"],title:"_Text-Only Report".loc(),paperIdBinding:SC.Binding.oneWay("Cv.paperController.id"),href:function(){return"/newreport.asp?lang=%@&oid=%@&ft=1&bypass_cv=1".fmt(Cv.get("lang"),Cv.paperController.get("id"))
}.property("paperId").cacheable(),toolTip:"_Navigate to text-only Originality Report".loc()}),applicationView:Dv.ApplicationView.design({layout:{top:0,bottom:0,left:0,right:0},classController:Cv.classController,assignmentsController:Cv.assignmentsController,assignmentStudentsController:Cv.assignmentStudentsController,assignmentController:Cv.assignmentController,paperController:Cv.paperController,paperTextSelectionController:Cv.paperTextSelectionController,servicesController:Cv.servicesController,zoomController:Cv.zoomController}),loadingView:Ip.LoadingView.design({layerId:"loading_mask",loadingText:"_Document Viewer is loading...".loc(),classNames:["application-loading"],firstPageLoadedBinding:SC.Binding.bool("Cv.paperView.pageListView.firstPageHasLoaded"),dprStatusBinding:"Cv.paperController.dprStatusCode",isVisible:function(){var a=this.get("dprStatus");
if(this.get("firstPageLoaded")){this._hasBeenHidden=YES;return NO}else{if(((a===0)||(a>0))&&(a!==Cv.DPR_CONSTANTS.DPR_SUCCESS)){this._hasBeenHidden=YES;
return NO}else{if(this._hasBeenHidden){return NO}}}return YES}.property("firstPageLoaded","dprStatus").cacheable(),isVisibleDidChange:function(){Cv.loadingViewController.set("isShowing",this.get("isVisible"))
}.observes("isVisible"),stopBenchMark:function(){if(!this._hasBenchmarked&&this.get("firstPageLoaded")){try{SC.Benchmark.end("applicationStartup");
var c=SC.Benchmark._statFor("applicationStartup").amt;var b=SC.Benchmark._statFor("applicationBootStrap").amt;
var a=b+c;LoadingTimer.returnResults({pageLoadDuration:b,appLoadDuration:c,userType:Cv.get("inStudentMode")?"student":"instructor",readId:Cv.paperController.get("id")});
this._hasBenchmarked=true}catch(d){console.log("could not gather startup info")}}}.observes("firstPageLoaded")}),_userFirstTime:function(){if(Cv.config.get("HIDE_FIRST_TIME_USER_MESSAGE")){return
}if(!this.get("bypassFirstTimeMessage")&&!this.get("firstTimeMessageDisplayed")&&this.get("classProducts")){var c=this.get("classProducts")[3]===0;
var b=SC.PanelPane.extend({layout:{width:720,height:500,centerX:0,centerY:0},classNames:"interstitial",userBinding:"Cv.userController.content",contentView:SC.View.extend({childViews:"messageView checkboxView buttonView".w(),messageView:SC.View.design({layout:{top:10,right:30,bottom:10,left:30},render:function(d,e){d.push("<a href=\"#\" onclick=\"window.open('http://www.turnitin.com/static/videos/support_walkthrough.html', 'Turnitin', 'height=600,width=980,scrollbars=no,resizable=no');return false;\" class=\"interstitial-videolink\">").push("_Watch a 4-minute walkthrough".loc()).push("</a>");
d.push('<div class="interstitial-gettingstarted">').push("<h1>").push("_Getting Started".loc()).push("</h1>").push("</div>");
if(c){d.push('<div class="interstitial-comments">').push("<h2>").push("_Comments".loc()).push("</h2>").push("_Click anywhere in the paper to leave a comment".loc()).push("</div>");
d.push('<div class="interstitial-originalityreport">').push("<h2>").push("_Originality Report".loc()).push("</h2>").push("_See where text in the paper matches other sources".loc()).push("</div>");
d.push('<div class="interstitial-quickmarks">').push("<h2>").push("_QuickMark".loc()).push("</h2>").push("_Save time by dragging and dropping your favorite comments on the paper".loc()).push("</div>")
}else{d.push('<div class="interstitial-similarity">').push("<h2>").push("_Similarity".loc()).push("</h2>").push("_See how much of the paper's text matches other sources".loc()).push("</div>");
d.push('<div class="interstitial-sources">').push("<h2>").push("_Sources".loc()).push("</h2>").push("_View all the sources that match a section of text".loc()).push("</div>");
d.push('<div class="interstitial-comparisons">').push("<h2>").push("_Comparisons".loc()).push("</h2>").push("_Easily compare the paper and source texts".loc()).push("</div>")
}d.push('<div class="interstitial-emboss">');d.push('<div class="interstitial-pill bevel-bottom">').push("_View all services and paper layers in a single place. Check the top left.".loc()).push("</div>");
d.push('<div class="interstitial-olde">').push("_Text-only Originality Report and Old GradeMark can be found at the bottom right".loc()).push("</div>");
d.push("</div>")}}),checkboxView:SC.CheckboxView.design({layout:{height:22,left:10,bottom:10,width:400},valueBinding:"Cv.userController.bypassFirstTimeMessage",displayTitle:"_Don't show this message again.".loc()}),buttonView:SC.ButtonView.design({layout:{bottom:10,right:10,height:30,width:70},classNames:"close",title:"_Close".loc(),action:"_remove"})}),_remove:function(){this.get("user").commitRecord();
this.remove()}}).loc(Ip.getLocalizationHash("Cv.interstitialPane"));var a=b.create();
a.append();this.set("firstTimeMessageDisplayed",YES)}}.observes("classProducts","bypassFirstTimeMessage"),audioPlayerSwfView:SC.View.design({layout:{height:1,width:1,bottom:0,left:0},isSWFLoaded:NO,didAppendToDocument:function(){if(Cv.config.get("CAN_GET_VOICE_COMMENTS")&&!this.get("isSWFLoaded")){Cv.audioPlayerController.initializePlayer(this.get("layer"));
this.set("isSWFLoaded",YES)}}.observes("Cv.config.CAN_GET_VOICE_COMMENTS")})})});
sc_require("core");SC.DateTime.dayNames="_SC.DateTime.dayNames".loc().w();SC.DateTime.abbreviatedDayNames="_SC.DateTime.abbreviatedDayNames".loc().w();
SC.DateTime.monthNames="_SC.DateTime.monthNames".loc().w();SC.DateTime.abbreviatedMonthNames="_SC.DateTime.abbreviatedMonthNames".loc().w();
Dv.main=function main(){document.getElementsByTagName("html")[0].lang=SC.Locale.currentLanguage;
Dv.getPath("mainPage.mainPane").append();Cv.applicationView=Dv.getPath("mainPage.mainPane.applicationView");
Cv.paperView=Cv.applicationView.get("paperView");if(use_fixtures){config={userId:10,paperId:1}
}else{var b=Ip.getQueryStringParameter("o")||49348116;var c=Ip.getQueryStringParameter("u")||9509520;
config={userId:c,paperId:b}}Qmlib.store=Dv.store;RubricManagerCore.store=Dv.store;
Cv.store=Dv.store;var d=Dv.store.find(Cv.Paper,b);Cv.paperController.set("content",d);
var e=Ip.getQueryStringParameter("student_user")==1?Cv.Student:Cv.User;var a=Dv.store.find(e,c);
Cv.userController.set("content",a);Dv.preloadImages()};Dv.preloadImages=function(){SC.imageCache.loadImage("https://www.turnitincdn.com/800404/static.turnitin.com/cv/20141205.1016/sproutcore/desktop/en_us/A/images/icons/shared.png");
return};SC.mixin(SC.RecordArray.prototype,{isReady:function(){return(this.get("status")&SC.Record.READY)!==0
}.property("status").cacheable()});SC.mixin(SC.Record.prototype,{isReady:function(){return(this.get("status")&SC.Record.READY)!==0
}});SC.mixin(SC.XHRResponse.prototype,Ip.XHRResponse);function main(){Dv.main()};